var images = new Array(
	["arine-mia.jpg","Arine and Mia, ShoujoAi.com Mascots"],
	["kuroko-mikoto.jpg","Kuroko and Mikoto from A Certain Scientific Railgun"],
	["uiharu-saten.jpg","Uiharu and Saten from A Certain Scientific Railgun"],
	["budoko-misaki.jpg","Budoko and Misaki from Akikan!"],
	["yell-najimi.jpg","Yell and Najimi from Akikan!"],
	["faye-sophia.jpg","Faye and Sophia from Another Lady Innocent"],
	["akira-fumi.jpg","Akira and Fumi from Aoi Hana"],
	["yasuko-fumi.jpg","Yasuko and Fumi from Aoi Hana"],
	["nami-syouko.jpg","Nami and Syouko from Aoi Shiro"],
	["syouko-kaya.jpg","Syouko and Kaya from Aoi Shiro"],
	["yasumi-syouko.jpg","Syouko and Yasumi from Aoi Shiro"],
	["akira-aika.jpg","Akira and Aika from Aria"],
	["alice-athena.jpg","Alice and Athena from Aria"],
	["alicia-akari.jpg","Alicia and Akari from Aria"],
	["kaorin-sakaki.jpg","Kaorin and Sakaki from Azumanga Daioh"],
	["kagura-sakaki.jpg","Kagura and Sakaki from Azumanga Daioh"],
	["akari-kris.jpg","Akari and Kris from Battle Athletes Victory"],
	["ichino-akari.jpg","Ichino and Akari from Battle Athletes Victory"],
	["hagino-mari.jpg","Hagino and Mari from Blue Drop"],
	["jo-meg.jpg","Jo and Meg from Burst Angel"],
	["yukino-kanade.jpg","Yukino and Kanade from Candy Boy"],
	["maria-canaan.jpg","Maria and Canaan from Canaan"],
	["tomoyo-sakura.jpg","Tomoyo and Sakura from Card Captor Sakura"],
	["shiori-carol.jpg","Shiori and Carol from Chirality"],
	["rosette-asmaria.jpg","Rosette and Asmaria from Chrno Crusade"],
	["yuri-kei.jpg","Yuri and Kei from Dirty Pair"],
	["ellis-nadie.jpg","Ellis and Nadie from El Cazador de la Bruja"],
	["lucy-aiko.jpg","Lucy and Aiko from Elfen Lied"],
	["cass-veronica.jpg","Cass and Veronica from Fallout: New Vegas"],
	["rin-saber.jpg","Rin and Saber from Fate/Stay Night"],
	["tifa-aeris.jpg","Tifa and Aeris from Final Fantasy VII"],
	["rikku-paine.jpg","Rikku and Paine from Final Fantasy X-2"],
	["agrias-ovelia.jpg","Agrias and Ovelia from Final Fantasy Tactics"],
	["kagura-yomi.jpg","Kagura and Yomi from Ga Rei Zero"],
	["mari-akko.jpg","Mari and Akko from Girl Friends"],
	["jiyu-freesha.jpg","Jiyu and Freesha from Jubei-chan"],
	["layla-sora.jpg","Layla and Sora from Kaleido Star"],
	["sora-rosetta.jpg","Sora and Rosetta from Kaleido Star"],
	["mika-kana.jpg","Mika and Kana from Kanamemo"],
	["chikane-himeko.jpg","Chikane and Himeko from Kannazuki no Miko"],
	["hazumu-tomari.jpg","Hazumu and Tomari from Kashimashi"],
	["hazumu-yasuna.jpg","Hazumu and Yasuna from Kashimashi"],
	["eclair-lumiere.jpg","Eclair and Lumiere from Kiddy Grade"],
	["kannu-rinrin.jpg","Kannu and Rinrin from Koihime Musou"],
	["naru-shinobu.jpg","Naru and Shinobu from Love Hina"],
	["yamato-kouya.jpg","Kouya and Yamato from Loveless"],
	["konata-kagami.jpg","Konata and Kagami from Lucky Star"],
	["fate-nanoha.jpg","Fate and Nanoha from Magical Girl Lyrical Nanoha"],
	["teana-subaru.jpg","Teana and Subaru from Magical Girl Lyrical Nanoha StrikerS"],
	["mai-natsuki.jpg","Mai and Natsuki from Mai HiME"],
	["shizuru-natsuki.jpg","Shizuru and Natsuki from Mai HiME"],
	["arika-mashiro.jpg","Arika and Mashiro from Mai Otome"],
	["haruka-yukino.jpg","Haruka and Yukino from Mai Otome"],
	["nina-arika.jpg","Nina and Arika from Mai Otome"],
	["eriko-rei.jpg","Eriko and Rei from Maria-sama ga Miteru"],
	["noriko-shimako.jpg","Noriko and Shimako from Maria-sama ga Miteru"],
	["rei-yoshino.jpg","Rei and Yoshino from Maria-sama ga Miteru"],
	["sachiko-yumi.jpg","Sachiko and Yumi from Maria-sama ga Miteru"],
	["shimako-sei.jpg","Shimako and Sei from Maria-sama ga Miteru"],
	["shimako-yoshino.jpg","Shimako and Yoshino from Maria-sama ga Miteru"],
	["mill-maze.jpg","Mill and Maze from Maze"],
	["alita-falis.jpg","Alita and Falis from Murder Princess"],
	["maya-ritsuko.jpg","Maya and Ritsuko from Neon Genesis Evangelion"],
	["asuka-rei.jpg","Asuka and Rei from Neon Genesis Evangelion"],
	["Zelda-Peach.jpg","Zelda and Peach from Nintendo"],
	["kirika-mireille.jpg","Mireille and Kirika from Noir"],
	["shia-misha.jpg","Shia and Misha from PitaTen"],
	["elysse-tita.jpg","Elysse and Tita from Plastic Little"],
	["honoka-nagisa.jpg","Honoka and Nagisa from Pretty Cure"],
	["ranma-akane.jpg","Ranma and Akane from Ranma 1/2"],
	["yomiko-nancy.jpg","Yomiko and Nancy from Read or Die"],
	["yomiko-nenene.jpg","Yomiko and Nenene from Read or Die"],
	["anthy-utena.jpg","Anthy and Utena from Revolutionary Girl Utena"],
	["juri-shiori.jpg","Juri and Shiori from Revolutionary Girl Utena"],
	["ami-mako.jpg","Ami and Makoto from Sailor Moon"],
	["chibiusa-hotaru.jpg","ChibiUsa and Hotaru from Sailor Moon"],
	["michiru-haruka.jpg","Michiru and Haruka from Sailor Moon"],
	["minako-rei.jpg","Minako and Rei from Sailor Moon"],
	["minako-usagi.jpg","Minako and Usagi from Sailor Moon"],
	["rei-setsuna.jpg","Rei and Setsuna from Sailor Moon"],
	["hisa-mihoko.jpg","Hisa and Mihoko from Saki"],
	["mako-hisa.jpg","Mako and Hisa from Saki"],
	["nodoka-saki.jpg","Nodoka and Saki from Saki"],
	["touka-hajime.jpg","Touka and Hajime from Saki"],
	["yumi-momoko.jpg","Yumi and Momoko from Saki"],
	["sumika-ushio.jpg","Sumika and Ushio from Sasameki Koto"],
	["lain-lain.jpg","Lain and Lain from Serial Experiments Lain"],
	["setsuna-kuu.jpg","Setsuna and Kuu from Shattered Angels"],
	["aerxneviril.jpg","Aer and Neviril from Simoun"],
	["amuria-neviriru.jpg","Amuria and Neville from Simoun"],
	["naga-lina.jpg","Naga and Lina from Slayers"],
	["kaede-sara.jpg","Kaede and Sara from Sono Hanabira ni Kuchizuke Wo"],
	["mai-reo.jpg","Mai and Reo from Sono Hanabira ni Kuchizuke Wo"],
	["nanami-yuuna.jpg","Nanami and Yuuna from Sono Hanabira ni Kuchizuke Wo"],
	["shizuku-eris.jpg","Shizuku and Eris from Sono Hanabira Ni Kuchizuke Wo"],
	["sophitia-xianghua.jpg","Sophitia and Xianghua from Soul Calibur"],
	["arisa-shima.jpg","Arisa and Shima from Stellvia of the Universe"],
	["ayaka-yayoi.jpg","Ayaka and Yayoi from Stellvia of the Universe"],
	["hikari-amane.jpg","Hikari and Amane from Strawberry Panic"],
	["shizuma-nagisa.jpg","Shizuma and Nagisa from Strawberry Panic"],
	["tamao-nagisa.jpg","Tamao and Nagisa from Strawberry Panic"],
	["kurumi-saki.jpg","Kurumi and Saki from Steel Angel Kurumi"],
	["minna-mio.jpg","Minna and Mio from Strike Witches"],
	["sanya-eila.jpg","Sanya and Eila from Strike Witches"],
	["lynne-yoshika.jpg","Yoshika and Lynne from Strike Witches"],
	["sugar-pratty.jpg","Sugar and Pratty from Summon Night: Swordcraft Story"],
	["sasara-tamaki.jpg","Sasara and Tamaki from To Heart"],
	["daiyousei-cirno.jpg","Daiyousei and Cirno from Touhou Project"],
	["marisa-alice.jpg","Marisa and Alice from Touhou Project"],
	["marisa-patchouli.jpg","Marisa and Patchouli from Touhou Project"],
	["marisa-reimu.jpg","Marisa and Reimu from Touhou Project"],
	["mokou-kaguya.jpg","Mokou and Kaguya from Touhou Project"],
	["sakuya-remilia.jpg","Sakuya and Remilia from Touhou Project"],
	["suwako-kanako.jpg","Suwako and Kanako from Touhou Project"],
	["yukari-reimu.jpg","Yukari and Reimu from Touhou Project"],
	["yuyuko-youmu.jpg","Yuyuko and Youmu from Touhou Project"],
	["yuyuko-yukari.jpg","Yuyuko and Yukari from Touhou Project"],
	["miku-luka.jpg","Miku and Luka from Vocaloid"],
	["hazuki-hatsumi.jpg","Hazuki and Hatsumi from Yami to Boushi to hon no Tabibito"],
	["miyuki-natsume.jpg","Miyuki and Natsumi from You\'re Under Arrest"],
	["mone-mizuki.jpg","Mone and Mizuki from Yumeria"]
);

function getBase()
{
	var url = document.getElementsByTagName("img")[0].src;
	return url.split("/").slice(0, -2).join("/");
}

function randomImage()
{
        var ranNum = Math.floor(Math.random()*images.length);
        var imageCode = '<img src="' + getBase() + '/images/shuffle/' + images[ranNum][0] + '" alt="' + images[ranNum][1] + '"><br><div class="frame" title="' + images[ranNum][1] + '" onClick="parent.location=\'' + getBase() + '/images.shtml\'">&nbsp;</div>';
        document.getElementById("imagespace").innerHTML = imageCode;
}

function printList()
{
        var listcode = '';
        for ( i=0; i<images.length; i++) {
                listcode += '<a href="' + getBase() + '/images/shuffle/' + images[i][0] + '">' + images[i][1] + '</a><br>';
        }
        document.getElementById("listspace").innerHTML = listcode;
}

